// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcueivsmbrdroyihkrap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdWVpdnNtYnJkcm95aWhrcmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjM4NTEsImV4cCI6MjA2MTUzOTg1MX0.T6AAKqyClHKjqcd9rx6KiUml4NCFYMuwh8c8DrXS5OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);